## Import Libraries

In [1]:
import pandas as pd
import os
import requests
import json
from datetime import datetime

## Load API Key

In [2]:
api_key = os.environ['VORTEXA_API_KEY']

## 1. Access Signals API via VesselSummary

This endpoint provides the Vessel Summary (location represented in lat long, draught, heading etc) for a given snapshot.

In [3]:
list_of_vessels = ['9297319', '9398072']
timestamp = datetime(2024,5,20)

In [7]:
def extract_vessel_summary(list_of_vessels, timestamp):
    URL = "https://api.vortexa.com/v6/signals/vessel-summary"
    timestamp_iso = timestamp.isoformat()
    
    ## Make API calls
    PARAMS = {
        'apikey':api_key,
        'timestamp':timestamp_iso,
        'vessel_id': list_of_vessels
    }
    r = requests.get(url = URL, params = PARAMS)
    data = r.json()
    return data

In [8]:
data = extract_vessel_summary(list_of_vessels,timestamp)

In [9]:
data

{'total': 2,
 'data': [{'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-20T00:45:12.000Z',
   'lat': 18.03962367,
   'lon': 118.08548064,
   'speed': 13,
   'heading': 221,
   'declared_destination': 'SG SIN',
   'declared_eta': '2024-05-24T12:00:00.000Z'},
  {'vessel_id': 'd3e9302f6a763df8',
   'timestamp': '2024-05-20T00:00:04.000Z',
   'lat': 22.46878958,
   'lon': 120.28884751,
   'speed': 0.1,
   'heading': 152.7,
   'draught': 15,
   'declared_destination': 'TW SHL',
   'declared_eta': '2024-05-16T02:00:00.000Z'}],
 'metadata': []}

In [10]:
json_data = data['data']
df = pd.DataFrame(json_data)
df

,vessel_id,timestamp,lat,lon,speed,heading,declared_destination,declared_eta,draught
0,357c920e329aaa91,2024-05-20T00:45:12.000Z,18.039624,118.085481,13.0,221.0,SG SIN,2024-05-24T12:00:00.000Z,NaN
1,d3e9302f6a763df8,2024-05-20T00:00:04.000Z,22.468790,120.288848,0.1,152.7,TW SHL,2024-05-16T02:00:00.000Z,15.0

## 2. Access Signals API via VesselPosition

This endpoint provides you the vessel trails.

In [11]:
list_of_vessels = ['9297319']
start_timestamp = datetime(2024,5,15)
end_timestamp = datetime(2024,5,20)
interval = '1h' # "5m","10m","15m","1h","3h","6h","1d","3d","7d"

In [12]:
def extract_vessel_positions(list_of_vessels, start_timestamp, end_timestamp, interval):
    URL = "https://api.vortexa.com/v6/signals/vessel-positions"
    start_timestamp_iso = start_timestamp.isoformat()
    end_timestamp_iso = end_timestamp.isoformat()
    ## Make API calls
    PARAMS = {
        'apikey':api_key,
        'time_min':start_timestamp_iso,
        'time_max': end_timestamp_iso,
        'interval': interval,
        'vessel_id': list_of_vessels
    }
    r = requests.get(url = URL, params = PARAMS)
    data = r.json()
    return data

In [13]:
data = extract_vessel_positions(list_of_vessels, start_timestamp, end_timestamp, interval)
data

{'total': 120,
 'data': [{'lat': 29.79916772,
   'lon': 122.15970835,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T00:00:00.000Z',
   'heading': 142,
   'speed': 0},
  {'lat': 29.79916772,
   'lon': 122.16279513,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T01:00:00.000Z',
   'heading': 322,
   'speed': 0},
  {'lat': 29.79916772,
   'lon': 122.15974905,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T02:00:00.000Z',
   'heading': 178,
   'speed': 0.1},
  {'lat': 29.79916772,
   'lon': 122.1597694,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T03:00:00.000Z',
   'heading': 182,
   'speed': 0},
  {'lat': 29.79916772,
   'lon': 122.1597287,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T04:00:00.000Z',
   'heading': 136,
   'speed': 0},
  {'lat': 29.79916772,
   'lon': 122.15974905,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T05:00:00.000Z',
   'heading': 140.3,
   'speed': 0},
  {'lat': 29.79916772,
   'lon': 122.15978975,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T06:00:00.000Z',
   'heading': 230.3,
   'speed': 0},
  {'lat': 29.79916772,
   'lon': 122.1597694,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T07:00:00.000Z',
   'heading': 147.5,
   'speed': 0},
  {'lat': 29.79916772,
   'lon': 122.15978975,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T08:00:00.000Z',
   'heading': 194,
   'speed': 0},
  {'lat': 29.79916772,
   'lon': 122.1598101,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T09:00:00.000Z',
   'heading': 275.4,
   'speed': 0},
  {'lat': 29.79916772,
   'lon': 122.1597287,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T10:00:00.000Z',
   'heading': 348,
   'speed': 0},
  {'lat': 29.79916772,
   'lon': 122.15978975,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T11:00:00.000Z',
   'heading': 122,
   'speed': 0},
  {'lat': 29.79916772,
   'lon': 122.15974905,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T12:00:00.000Z',
   'heading': 113.8,
   'speed': 0},
  {'lat': 29.79373982,
   'lon': 122.1358775,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T13:00:00.000Z',
   'heading': 342,
   'speed': 3},
  {'lat': 29.82087932,
   'lon': 122.11762322,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T14:00:00.000Z',
   'heading': 327.6,
   'speed': 1},
  {'lat': 29.82087932,
   'lon': 122.11952971,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T15:00:00.000Z',
   'heading': 326.9,
   'speed': 0},
  {'lat': 29.82087932,
   'lon': 122.12012018,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T16:00:00.000Z',
   'heading': 335,
   'speed': 0.1},
  {'lat': 29.82359327,
   'lon': 122.11931326,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T17:00:00.000Z',
   'heading': 247,
   'speed': 0},
  {'lat': 29.82630722,
   'lon': 122.11934139,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T18:00:00.000Z',
   'heading': 165,
   'speed': 0},
  {'lat': 29.82630722,
   'lon': 122.12263261,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T19:00:00.000Z',
   'heading': 114.7,
   'speed': 0},
  {'lat': 29.82630722,
   'lon': 122.12263261,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T20:00:00.000Z',
   'heading': 336,
   'speed': 0},
  {'lat': 29.82359327,
   'lon': 122.12466117,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T21:00:00.000Z',
   'heading': 4.1,
   'speed': 0},
  {'lat': 29.82359327,
   'lon': 122.12376513,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T22:00:00.000Z',
   'heading': 312,
   'speed': 0},
  {'lat': 29.82359327,
   'lon': 122.12309311,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-15T23:00:00.000Z',
   'heading': 73.1,
   'speed': 0},
  {'lat': 29.82087932,
   'lon': 122.12355377,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T00:00:00.000Z',
   'heading': 221,
   'speed': 0.2},
  {'lat': 29.82087932,
   'lon': 122.1203238,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T01:00:00.000Z',
   'heading': 183.9,
   'speed': 0.2},
  {'lat': 29.82087932,
   'lon': 122.12012018,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T02:00:00.000Z',
   'heading': 56.7,
   'speed': 0.3},
  {'lat': 29.82087932,
   'lon': 122.11845805,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T03:00:00.000Z',
   'heading': 142.7,
   'speed': 0.1},
  {'lat': 29.82087932,
   'lon': 122.11526877,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T04:00:00.000Z',
   'heading': 212,
   'speed': 0},
  {'lat': 29.83987697,
   'lon': 122.1189856,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T05:00:00.000Z',
   'heading': 236.9,
   'speed': 5.8},
  {'lat': 29.81002352,
   'lon': 122.07689255,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T06:00:00.000Z',
   'heading': 47,
   'speed': 0},
  {'lat': 29.81002352,
   'lon': 122.07699428,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T07:00:00.000Z',
   'heading': 319.5,
   'speed': 0},
  {'lat': 29.81002352,
   'lon': 122.0769129,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T08:00:00.000Z',
   'heading': 73,
   'speed': 0},
  {'lat': 29.81002352,
   'lon': 122.07681117,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T09:00:00.000Z',
   'heading': 355.3,
   'speed': 0.1},
  {'lat': 29.81002352,
   'lon': 122.07646529,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T10:00:00.000Z',
   'heading': 125,
   'speed': 0.2},
  {'lat': 29.81002352,
   'lon': 122.07634321,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T11:00:00.000Z',
   'heading': 297.7,
   'speed': 0},
  {'lat': 29.81002352,
   'lon': 122.07894206,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T12:00:00.000Z',
   'heading': 142,
   'speed': 0},
  {'lat': 29.81002352,
   'lon': 122.07822997,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T13:00:00.000Z',
   'heading': 265.5,
   'speed': 0},
  {'lat': 29.80459562,
   'lon': 122.0730222,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T14:00:00.000Z',
   'heading': 136,
   'speed': 0},
  {'lat': 29.80730957,
   'lon': 122.07422233,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T15:00:00.000Z',
   'heading': 1,
   'speed': 0},
  {'lat': 29.80730957,
   'lon': 122.07196931,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T16:00:00.000Z',
   'heading': 255.9,
   'speed': 0},
  {'lat': 29.80730957,
   'lon': 122.07192863,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T17:00:00.000Z',
   'heading': 184.9,
   'speed': 0},
  {'lat': 29.81002352,
   'lon': 122.07599734,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T18:00:00.000Z',
   'heading': 73,
   'speed': 0.1},
  {'lat': 29.81002352,
   'lon': 122.07628218,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T19:00:00.000Z',
   'heading': 98,
   'speed': 0},
  {'lat': 29.81002352,
   'lon': 122.0763839,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T20:00:00.000Z',
   'heading': 173,
   'speed': 0},
  {'lat': 29.81002352,
   'lon': 122.0792269,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T21:00:00.000Z',
   'heading': 272.6,
   'speed': 0},
  {'lat': 29.80730957,
   'lon': 122.07709068,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T22:00:00.000Z',
   'heading': 217,
   'speed': 0},
  {'lat': 29.81002352,
   'lon': 122.07875895,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-16T23:00:00.000Z',
   'heading': 286,
   'speed': 0.1},
  {'lat': 29.80459562,
   'lon': 122.07653636,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T00:00:00.000Z',
   'heading': 168,
   'speed': 3.6},
  {'lat': 29.81816537,
   'lon': 122.12172125,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T01:00:00.000Z',
   'heading': 310,
   'speed': 1.9},
  {'lat': 29.82359327,
   'lon': 122.11754935,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T02:00:00.000Z',
   'heading': 149.5,
   'speed': 0.1},
  {'lat': 29.82359327,
   'lon': 122.11716245,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T03:00:00.000Z',
   'heading': 283.5,
   'speed': 0},
  {'lat': 29.82359327,
   'lon': 122.1176919,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T04:00:00.000Z',
   'heading': 19.7,
   'speed': 0.1},
  {'lat': 29.82630722,
   'lon': 122.11714987,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T05:00:00.000Z',
   'heading': 107.8,
   'speed': 0},
  {'lat': 29.82630722,
   'lon': 122.11561004,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T06:00:00.000Z',
   'heading': 183.6,
   'speed': 0},
  {'lat': 29.72860503,
   'lon': 122.22474775,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T07:00:00.000Z',
   'heading': 122,
   'speed': 12.2},
  {'lat': 29.68246788,
   'lon': 122.42566153,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T08:00:00.000Z',
   'heading': 94.9,
   'speed': 12.8},
  {'lat': 29.65804234,
   'lon': 122.70430069,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T09:00:00.000Z',
   'heading': 94,
   'speed': 14.9},
  {'lat': 29.5359146,
   'lon': 122.90611447,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T10:00:00.000Z',
   'heading': 135.7,
   'speed': 13},
  {'lat': 29.36222182,
   'lon': 123.06894578,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T11:00:00.000Z',
   'heading': 140,
   'speed': 13.2},
  {'lat': 29.17767324,
   'lon': 123.20546952,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T12:00:00.000Z',
   'heading': 181,
   'speed': 13},
  {'lat': 28.96327121,
   'lon': 123.18214618,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T13:00:00.000Z',
   'heading': 189,
   'speed': 13.3},
  {'lat': 28.72987154,
   'lon': 123.15235342,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T14:00:00.000Z',
   'heading': 184,
   'speed': 13.3},
  {'lat': 28.52361136,
   'lon': 123.12777935,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T15:00:00.000Z',
   'heading': 186,
   'speed': 13.3},
  {'lat': 28.30649539,
   'lon': 123.09874653,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T16:00:00.000Z',
   'heading': 183,
   'speed': 13},
  {'lat': 28.08937941,
   'lon': 123.08738047,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T17:00:00.000Z',
   'heading': 186,
   'speed': 13.6},
  {'lat': 27.84783789,
   'lon': 123.0545771,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T18:00:00.000Z',
   'heading': 187,
   'speed': 13},
  {'lat': 27.62529401,
   'lon': 123.02198938,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T19:00:00.000Z',
   'heading': 187,
   'speed': 13},
  {'lat': 27.40546409,
   'lon': 122.99761847,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T20:00:00.000Z',
   'heading': 185,
   'speed': 13.8},
  {'lat': 27.16663651,
   'lon': 122.96866076,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T21:00:00.000Z',
   'heading': 186,
   'speed': 13.9},
  {'lat': 26.93052289,
   'lon': 122.93858994,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T22:00:00.000Z',
   'heading': 185,
   'speed': 14},
  {'lat': 26.68898136,
   'lon': 122.91194802,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-17T23:00:00.000Z',
   'heading': 188,
   'speed': 14},
  {'lat': 26.52614438,
   'lon': 122.88968661,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T00:00:00.000Z',
   'heading': 184,
   'speed': 8.9},
  {'lat': 26.3578795,
   'lon': 122.87482768,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T01:00:00.000Z',
   'heading': 186,
   'speed': 10},
  {'lat': 26.14890537,
   'lon': 122.85031141,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T02:00:00.000Z',
   'heading': 185,
   'speed': 13},
  {'lat': 25.9317894,
   'lon': 122.82415192,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T03:00:00.000Z',
   'heading': 187,
   'speed': 13},
  {'lat': 25.71195947,
   'lon': 122.79155459,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T04:00:00.000Z',
   'heading': 185,
   'speed': 12.7},
  {'lat': 25.52469694,
   'lon': 122.78071988,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T05:00:00.000Z',
   'heading': 184,
   'speed': 13},
  {'lat': 25.29129727,
   'lon': 122.74754864,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T06:00:00.000Z',
   'heading': 180,
   'speed': 12},
  {'lat': 25.10674869,
   'lon': 122.72903488,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T07:00:00.000Z',
   'heading': 188,
   'speed': 10},
  {'lat': 24.93305591,
   'lon': 122.70850381,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T08:00:00.000Z',
   'heading': 183,
   'speed': 11},
  {'lat': 24.75936313,
   'lon': 122.70244922,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T09:00:00.000Z',
   'heading': 180,
   'speed': 11},
  {'lat': 24.5232495,
   'lon': 122.69531851,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T10:00:00.000Z',
   'heading': 185,
   'speed': 13.6},
  {'lat': 24.27899403,
   'lon': 122.69727544,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T11:00:00.000Z',
   'heading': 179,
   'speed': 14.7},
  {'lat': 24.03745251,
   'lon': 122.69568269,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T12:00:00.000Z',
   'heading': 175,
   'speed': 14.3},
  {'lat': 23.81490863,
   'lon': 122.70197097,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T13:00:00.000Z',
   'heading': 181,
   'speed': 13},
  {'lat': 23.59236475,
   'lon': 122.69510511,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T14:00:00.000Z',
   'heading': 179,
   'speed': 13},
  {'lat': 23.36710693,
   'lon': 122.69588082,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T15:00:00.000Z',
   'heading': 181,
   'speed': 13},
  {'lat': 23.14999095,
   'lon': 122.64266226,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T16:00:00.000Z',
   'heading': 199,
   'speed': 13},
  {'lat': 22.94644473,
   'lon': 122.55942786,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T17:00:00.000Z',
   'heading': 199,
   'speed': 13.9},
  {'lat': 22.7374706,
   'lon': 122.48207241,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T18:00:00.000Z',
   'heading': 199,
   'speed': 14},
  {'lat': 22.50135697,
   'lon': 122.39776598,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T19:00:00.000Z',
   'heading': 194,
   'speed': 14},
  {'lat': 22.30866655,
   'lon': 122.29900956,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T20:00:00.000Z',
   'heading': 211,
   'speed': 13.5},
  {'lat': 22.05898317,
   'lon': 122.23433461,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T21:00:00.000Z',
   'heading': 196,
   'speed': 14},
  {'lat': 21.8310114,
   'lon': 122.1449815,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T22:00:00.000Z',
   'heading': 195,
   'speed': 13.8},
  {'lat': 21.61389542,
   'lon': 122.06618315,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-18T23:00:00.000Z',
   'heading': 202,
   'speed': 14},
  {'lat': 21.46191424,
   'lon': 121.92683754,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T00:00:00.000Z',
   'heading': 236,
   'speed': 14.8},
  {'lat': 21.3940655,
   'lon': 121.81309838,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T01:00:00.000Z',
   'heading': 235,
   'speed': 4},
  {'lat': 21.36963995,
   'lon': 121.78063196,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T02:00:00.000Z',
   'heading': 239,
   'speed': 1},
  {'lat': 21.3614981,
   'lon': 121.74456145,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T03:00:00.000Z',
   'heading': 269,
   'speed': 1},
  {'lat': 21.29364936,
   'lon': 121.63254102,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T04:00:00.000Z',
   'heading': 233,
   'speed': 13},
  {'lat': 21.13624028,
   'lon': 121.4103971,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T05:00:00.000Z',
   'heading': 229,
   'speed': 13},
  {'lat': 21.00868464,
   'lon': 121.21689044,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T06:00:00.000Z',
   'heading': 237,
   'speed': 12},
  {'lat': 20.9028406,
   'lon': 121.04199191,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T07:00:00.000Z',
   'heading': 235,
   'speed': 12},
  {'lat': 20.77528496,
   'lon': 120.85310009,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T08:00:00.000Z',
   'heading': 234,
   'speed': 13},
  {'lat': 20.60973403,
   'lon': 120.63182794,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T09:00:00.000Z',
   'heading': 231,
   'speed': 13},
  {'lat': 20.4658947,
   'lon': 120.45957687,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T10:00:00.000Z',
   'heading': 228,
   'speed': 13},
  {'lat': 20.30034377,
   'lon': 120.29443245,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T11:00:00.000Z',
   'heading': 223,
   'speed': 13},
  {'lat': 20.13750678,
   'lon': 120.13504838,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T12:00:00.000Z',
   'heading': 221,
   'speed': 13.9},
  {'lat': 19.96110005,
   'lon': 119.96408371,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T13:00:00.000Z',
   'heading': 223,
   'speed': 14.4},
  {'lat': 19.80911887,
   'lon': 119.81594559,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T14:00:00.000Z',
   'heading': 223,
   'speed': 14},
  {'lat': 19.64899584,
   'lon': 119.65279244,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T15:00:00.000Z',
   'heading': 222,
   'speed': 13},
  {'lat': 19.43459381,
   'lon': 119.45447697,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T16:00:00.000Z',
   'heading': 221,
   'speed': 14},
  {'lat': 19.26090103,
   'lon': 119.28165099,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T17:00:00.000Z',
   'heading': 224,
   'speed': 14},
  {'lat': 19.08178035,
   'lon': 119.1026378,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T18:00:00.000Z',
   'heading': 223,
   'speed': 14.3},
  {'lat': 18.91622942,
   'lon': 118.94735211,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T19:00:00.000Z',
   'heading': 222,
   'speed': 14.4},
  {'lat': 18.72625294,
   'lon': 118.75505881,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T20:00:00.000Z',
   'heading': 223,
   'speed': 15.2},
  {'lat': 18.54713226,
   'lon': 118.58117774,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T21:00:00.000Z',
   'heading': 221,
   'speed': 14},
  {'lat': 18.35986973,
   'lon': 118.40035871,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T22:00:00.000Z',
   'heading': 223,
   'speed': 15.4},
  {'lat': 18.18074905,
   'lon': 118.22451677,
   'vessel_id': '357c920e329aaa91',
   'timestamp': '2024-05-19T23:00:00.000Z',
   'heading': 223,
   'speed': 14.4}],
 'metadata': [{'type': 'info', 'payload': 'Found 120 results'}]}

In [14]:
df2 = pd.DataFrame(data['data'])
df2

,lat,lon,vessel_id,timestamp,heading,speed
0,29.799168,122.159708,357c920e329aaa91,2024-05-15T00:00:00.000Z,142.0,0.0
1,29.799168,122.162795,357c920e329aaa91,2024-05-15T01:00:00.000Z,322.0,0.0
2,29.799168,122.159749,357c920e329aaa91,2024-05-15T02:00:00.000Z,178.0,0.1
3,29.799168,122.159769,357c920e329aaa91,2024-05-15T03:00:00.000Z,182.0,0.0
4,29.799168,122.159729,357c920e329aaa91,2024-05-15T04:00:00.000Z,136.0,0.0
...,...,...,...,...,...,...
115,18.916229,118.947352,357c920e329aaa91,2024-05-19T19:00:00.000Z,222.0,14.4
116,18.726253,118.755059,357c920e329aaa91,2024-05-19T20:00:00.000Z,223.0,15.2
117,18.547132,118.581178,357c920e329aaa91,2024-05-19T21:00:00.000Z,221.0,14.0
118,18.359870,118.400359,357c920e329aaa91,2024-05-19T22:00:00.000Z,223.0,15.4
119,18.180749,118.224517,357c920e329aaa91,2024-05-19T23:00:00.000Z,223.0,14.4

## Comparison between VesselSummary and VesselPositions

|- |Vessel Summary|Vessel Positions|
|----|----|-----|
|Pros|Have More fields (declared dest, declared eta, draught)|1 API call to plot vessel trails|
|Cons|Have to make more API calls for vessel trails|Lack of declared information|